/**
 * Event payload for when a new user is registered via the auth-service.
 * This event is published by auth-service after basic credential creation (e.g., email/password hash stored).
 * It signals other services, like user-service, to perform follow-up actions (e.g., create a user profile).
 */
export interface AuthUserRegisteredEvent {
  eventId: string;      // Unique ID for this specific event instance (e.g., UUID)
  timestamp: Date;      // ISO 8601 timestamp of when the event occurred
  userId: string;       // The ID of the newly registered user (generated by auth-service)
  email: string;        // User's email, confirmed at registration
  // Include any other essential data gathered during registration that other services might need immediately
  // e.g., initial preferences, referral code, etc. Keep it minimal.
}

/**
 * The name (routing key or topic) for the auth.user_registered event.
 * Format: <service>.<resource>.<action>
 */
export const AUTH_USER_REGISTERED_EVENT_NAME = 'auth.user.registered'; 